server:
  port: 9000
spring:
  application:
    name: coupon-gateway

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

zuul:
  prefix: /imooc
  routes:
    # CouponTemplate Microservice Route Configuration
    template:
      path: /coupon-template/**
      serviceId: eureka-client-coupon-template
      strip-prefix: false
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

# load balancing
ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000
